### ISSUE TITLE
add type hints

### ISSUE THREAD

**Issue by diljotgrewal** [mondrian-scwgs/csverve#4]
compatible with conventions outlined here
https://github.com/mondrian-scwgs/mondrian/blob/mondrian/docs/contribute/python_conventions.md

**Comment by eliko1991** [comment]
@diljotgrewal see updates on this branch https://github.com/mondrian-scwgs/csverve/tree/pandas_updates.

**Comment by diljotgrewal** [comment]
@eliko1991 can you please test with mypy to ensure the type checks work, and add dtypes for all variables.

**Comment by eliko1991** [comment]
@diljotgrewal added additional type checks and tested with mypy. Getting 9 errors that we need to discuss.
`csverve/extras.py:2: error: Skipping analyzing 'pandas': found module but no type hints or library stubs
csverve/extras.py:3: error: Skipping analyzing 'numpy': found module but no type hints or library stubs
csverve/helpers.py:16: error: Skipping analyzing 'pandas': found module but no type hints or library stubs
csverve/csverve.py:3: error: Skipping analyzing 'pandas': found module but no type hints or library stubs
csverve/csverve.py:3: note: See https://mypy.readthedocs.io/en/latest/running_mypy.html#missing-imports
csverve/csverve.py:421: error: Incompatible types in assignment (expression has type "Optional[List[str]]", variable has type "List[str]")
csverve/csverve.py:749: error: Incompatible types in assignment (expression has type "ValuesView[str]", variable has type "Union[List[str], Dict[str, str]]")
csverve/csverve.py:888: error: Incompatible types in assignment (expression has type "IrregularCsverveInput", variable has type "CsverveInput")
csverve/csverve.py:925: error: Incompatible types in assignment (expression has type "ValuesView[str]", variable has type "Dict[str, str]")
csverve/csverve.py:986: error: Incompatible types in assignment (expression has type "List[str]", variable has type "str")
Found 9 errors in 3 files (checked 5 source files)
`
